language: c

services:
  - docker

cache: ccache

script:
  - docker build -t ci -f .travis/Dockerfile .
  - docker run -w /repo -v $(pwd):/repo -v $HOME/.ccache:/opam/.ccache -it ci .travis/.travis-ci.sh

after_script:
  - bin/fetch-configlet
  - bin/configlet lint .
