services:
  - docker

before_script:
  - docker run -w /repo -v $(pwd):/repo --entrypoint "/bin/bash" -it ocaml/opam2:alpine-3.9-ocaml-4.06 .travis-ci.sh generate

script:
  - docker run -w /repo -v $(pwd):/repo --entrypoint "/bin/bash" -it ocaml/opam2:alpine-3.9-ocaml-4.07 .travis-ci.sh test

after_script:
  - bin/fetch-configlet
  - bin/configlet lint .
