services:
  - docker

script:
  - docker pull marionebl/ocaml-exercism-ci
  - docker build -t marionebl/ocaml-exercism-ci -f .travis/Dockerfile .
  - docker run -w /repo -v $(pwd):/repo -it marionebl/ocaml-exercism-ci .travis/.travis-ci.sh

after_script:
  - bin/fetch-configlet
  - bin/configlet lint .
