language: c

services:
  - docker

script:
  - docker run -w /repo -v $(pwd):/repo --entrypoint "/bin/bash" -it ocaml/opam2:alpine ".travis-ci.sh"
  - bin/fetch-configlet
  - bin/configlet lint .

env:
  - OCAML_VERSION=4.07.0 OPAM_VERSION=1.2.2
